### PR TITLE
feat!: drop support for node 10-13

### PR DESCRIPTION
**Pull request by philihp**

### CODE REVIEW

**Comment by ljharb** [comment]
lol lots of new features in node 14 you want to use here?

**Comment by philihp** [comment]
@ljharb lol nah... `jest` tends to throw a fit on versions of node outside of LTS and I kind of appreciate them for pushing us forward.

**Comment by philihp** [comment]
e.g. https://github.com/philihp/deneg-zero/pull/60

**Comment by ljharb** [comment]
imo using jest on packages is overkill, and the forced dropping of older versions is a huge negative ¯\\\_(ツ)_/¯ jest is for apps; i recommend tape for packages.

**Comment by philihp** [comment]
Cool, thanks. I'm down to give it a shot. Learning a new test/matcher syntax has a high coefficient of static friction, but if I'm gonna ever take it for a test drive, here is probably optimal.

**Pull request merged**
